name: Continuous-Deployment

on:  
  push:  
    branches:  
      - main  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Deploy to EC2  
        uses: appleboy/ssh-action@master  
        with:  
          host: 54.210.215.74  
          username: ubuntu  
          key: ${{ secrets.EC2_KEY }}  # Your EC2 SSH private key  
          script: |  
            cd /home/ubuntu/hngx-stage2-fastapi-book-project  
            git pull origin main  
            source venv/bin/activate  
            pip install -r requirements.txt  
            sudo systemctl restart uvicorn   
            sudo systemctl restart ngrok

