name: Continuous-Deployment  

on:  
  push:  
    branches:  
      - main  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Check out the repo  
        uses: actions/checkout@v2  
      - name: Deploy to EC2  
        run: ssh -i ${{ secrets.EC2_KEY }} ubuntu@54.210.215.74 'cd /home/ubuntu/hngx-stage2-fastapi-book-project && git pull && nohup uvicorn main:app
        env:  
          EC2_KEY: ${{ secrets.EC2_KEY }} 