name: Continuous-Deployment

on:  
  push:  
    branches:  
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 8000
          script: | 
            cd /home/ubuntu/hngx-stage2-fastapi-book-project  
            git pull origin main  
            source venv/bin/activate  
            pip install -r requirements.txt  
            sudo systemctl restart nginx
            sudo systemctl restart uvicorn   
            sudo systemctl restart ngrok
